/** IOC → ISO 3166-1 alpha-2 for flag images. Tennis-heavy, plus common ISO3 overlap. */
const IOC_TO_ISO2: Record<string, string> = {
  ALG: 'dz',
  AND: 'ad',
  ARG: 'ar',
  ARM: 'am',
  AUS: 'au',
  AUT: 'at',
  AZE: 'az',
  BAH: 'bs',
  BAR: 'bb',
  BEL: 'be',
  BIH: 'ba',
  BLR: 'by',
  BOL: 'bo',
  BOT: 'bw',
  BRA: 'br',
  BUL: 'bg',
  CAN: 'ca',
  CHI: 'cl',
  CHN: 'cn',
  COL: 'co',
  CRC: 'cr',
  CRO: 'hr',
  CYP: 'cy',
  CZE: 'cz',
  DEN: 'dk',
  DOM: 'do',
  ECU: 'ec',
  EGY: 'eg',
  ESA: 'sv',
  ESP: 'es',
  EST: 'ee',
  FIN: 'fi',
  FRA: 'fr',
  GBR: 'gb',
  GEO: 'ge',
  GER: 'de',
  GRE: 'gr',
  GUA: 'gt',
  HKG: 'hk',
  HON: 'hn',
  HUN: 'hu',
  INA: 'id',
  IND: 'in',
  IRL: 'ie',
  IRI: 'ir',
  ISR: 'il',
  ITA: 'it',
  JAM: 'jm',
  JPN: 'jp',
  KAZ: 'kz',
  KEN: 'ke',
  KOR: 'kr',
  KSA: 'sa',
  LAT: 'lv',
  LIB: 'lb',
  LIE: 'li',
  LTU: 'lt',
  LUX: 'lu',
  MAR: 'ma',
  MAS: 'my',
  MDA: 'md',
  MEX: 'mx',
  MNE: 'me',
  MON: 'mc',
  NED: 'nl',
  NGR: 'ng',
  NOR: 'no',
  NZL: 'nz',
  PAR: 'py',
  PER: 'pe',
  PHI: 'ph',
  POL: 'pl',
  POR: 'pt',
  PUR: 'pr',
  QAT: 'qa',
  ROU: 'ro',
  RSA: 'za',
  RUS: 'ru',
  SLO: 'si',
  SRB: 'rs',
  SUI: 'ch',
  SVK: 'sk',
  SWE: 'se',
  THA: 'th',
  TPE: 'tw',
  TUN: 'tn',
  TUR: 'tr',
  UAE: 'ae',
  UKR: 'ua',
  URU: 'uy',
  USA: 'us',
  UZB: 'uz',
  VEN: 've',
  VIE: 'vn',
  ZIM: 'zw',
};

export function tennisIocToIso2(ioc: string | null | undefined): string | null {
  const code = String(ioc || '')
    .trim()
    .toUpperCase();
  if (!code || code === 'UNK' || code === 'ITF') return null;
  return IOC_TO_ISO2[code] || null;
}

export function tennisFlagUrl(ioc: string | null | undefined): string | null {
  const iso2 = tennisIocToIso2(ioc);
  if (!iso2) return null;
  return `https://flagcdn.com/w40/${iso2}.png`;
}
