/** Players the tennis feed labels "World" (neutral). Keyed by API player id and name. */
export const NEUTRAL_IOC_BY_ID: Record<string, 'RUS' | 'BLR'> = {
  '43': 'RUS',
  '69': 'RUS',
  '199': 'BLR',
  '202': 'RUS',
  '223': 'BLR',
  '368': 'BLR',
  '415': 'RUS',
  '432': 'RUS',
  '435': 'RUS',
  '466': 'BLR',
  '468': 'RUS',
  '527': 'BLR',
  '574': 'RUS',
  '575': 'RUS',
  '650': 'RUS',
  '670': 'RUS',
  '757': 'RUS',
  '766': 'RUS',
  '776': 'RUS',
  '830': 'RUS',
  '896': 'BLR',
  '993': 'RUS',
  '1005': 'RUS',
  '1057': 'RUS',
  '1093': 'RUS',
  '1115': 'RUS',
  '1116': 'RUS',
  '1122': 'RUS',
  '1197': 'RUS',
  '1238': 'RUS',
  '1417': 'RUS',
  '1435': 'RUS',
  '1794': 'RUS',
  '1814': 'RUS',
  '1820': 'RUS',
  '1861': 'RUS',
  '1878': 'RUS',
  '1901': 'RUS',
  '1937': 'BLR',
  '1944': 'RUS',
  '1958': 'RUS',
  '1983': 'RUS',
  '1985': 'RUS',
  '1987': 'RUS',
  '1989': 'BLR',
  '2101': 'RUS',
  '2114': 'BLR',
  '2174': 'BLR',
  '2209': 'RUS',
  '2298': 'BLR',
  '2392': 'RUS',
  '2526': 'RUS',
  '2694': 'RUS',
  '2810': 'RUS',
  '2822': 'RUS',
  '2847': 'RUS',
  '4061': 'RUS',
  '5264': 'RUS',
  '5877': 'BLR',
  '6838': 'RUS',
  '7190': 'RUS',
  '7395': 'RUS',
  '7403': 'RUS',
  '7491': 'BLR',
  '9218': 'RUS',
  '9231': 'RUS',
  '9245': 'RUS',
  '9253': 'RUS',
  '9255': 'RUS',
  '9256': 'RUS',
  '9258': 'RUS',
  '9264': 'RUS',
  '9265': 'BLR',
  '9399': 'RUS',
  '9534': 'RUS',
  '10851': 'RUS',
  '10901': 'RUS',
  '12829': 'RUS',
  '13072': 'RUS',
  '13204': 'RUS',
  '13376': 'RUS',
  '13386': 'RUS',
  '13389': 'RUS',
  '13411': 'RUS',
  '13424': 'RUS',
  '13499': 'RUS',
  '13973': 'RUS',
  '13986': 'BLR',
  '14126': 'RUS',
  '14150': 'RUS',
  '14515': 'RUS',
  '14516': 'BLR',
  '14549': 'RUS',
  '14553': 'RUS',
  '14560': 'RUS',
  '14563': 'RUS',
  '14824': 'RUS',
  '14892': 'RUS',
  '18807': 'RUS',
  '19544': 'RUS',
  '21946': 'RUS',
  '23775': 'RUS',
  '23829': 'RUS',
  '23831': 'RUS',
  '23833': 'RUS',
  '24512': 'RUS',
  '32546': 'RUS',
  '36989': 'RUS',
  '37975': 'RUS',
  '38317': 'RUS',
  '38321': 'RUS',
  '38938': 'RUS',
  '38960': 'RUS',
  '39049': 'RUS',
  '39915': 'BLR',
  '40096': 'RUS',
  '40122': 'RUS',
  '40163': 'RUS',
  '40214': 'RUS',
  '40793': 'RUS',
  '49391': 'RUS',
  '49392': 'RUS',
  '49576': 'RUS',
  '49590': 'RUS',
  '51004': 'RUS',
  '51324': 'RUS',
  '51378': 'RUS',
  '51418': 'RUS',
  '51594': 'RUS',
  '52054': 'RUS',
  '52629': 'RUS',
  '52840': 'RUS',
  '54138': 'RUS',
  '55114': 'RUS',
  '57527': 'RUS',
  '57647': 'BLR',
  '59293': 'RUS',
  '60798': 'RUS',
  '61314': 'RUS',
  '61490': 'RUS',
  '62037': 'RUS',
  '62081': 'RUS',
  '62334': 'RUS',
  '63095': 'BLR',
  '63416': 'RUS',
  '63419': 'RUS',
  '66793': 'RUS',
  '66958': 'RUS',
  '67383': 'RUS',
  '67427': 'RUS',
  '67676': 'RUS',
  '68376': 'RUS',
  '68731': 'RUS',
  '72717': 'RUS',
  '73806': 'RUS',
  '74763': 'RUS',
  '75363': 'RUS',
  '75364': 'RUS',
  '75457': 'RUS',
  '75803': 'RUS',
  '76298': 'RUS',
  '76308': 'RUS',
  '76394': 'RUS',
  '76626': 'RUS',
  '76705': 'RUS',
  '76954': 'RUS',
  '76966': 'RUS',
  '77370': 'RUS',
  '77573': 'RUS',
  '77927': 'RUS',
  '79191': 'RUS',
  '80068': 'RUS',
  '81398': 'RUS',
  '81408': 'RUS',
  '81857': 'RUS',
  '82604': 'RUS',
  '82996': 'RUS',
  '83104': 'RUS',
  '84299': 'RUS',
  '86675': 'RUS',
  '87011': 'RUS',
  '87750': 'RUS',
  '88185': 'RUS',
  '88817': 'BLR',
  '89145': 'RUS',
  '89625': 'RUS',
  '90177': 'RUS',
  '90411': 'RUS',
  '90809': 'RUS',
  '91358': 'RUS',
  '92497': 'RUS',
  '92499': 'RUS',
  '92837': 'RUS',
  '93915': 'RUS',
  '101399': 'RUS',
  '101759': 'RUS',
  '101818': 'RUS',
  '102703': 'RUS',
  '102961': 'RUS',
  '103843': 'RUS',
  '106113': 'RUS',
  '108631': 'RUS',
  '108632': 'RUS',
  '108643': 'RUS',
  '108977': 'RUS',
};

export const NEUTRAL_IOC_BY_NAME: Record<string, 'RUS' | 'BLR'> = {
  "a. alekseychuk": 'RUS',
  "a. aleshchev": 'RUS',
  "a. anshba": 'RUS',
  "a. arifullina": 'RUS',
  "a. arzhankin": 'RUS',
  "a. bazderova": 'RUS',
  "a. bulatova": 'RUS',
  "a. chayka": 'RUS',
  "a. chekhov": 'RUS',
  "a. chepelev": 'RUS',
  "a. danilova": 'RUS',
  "a. dubinin": 'RUS',
  "a. efremova": 'RUS',
  "a. falei": 'BLR',
  "a. gasanova": 'RUS',
  "a. gureva": 'RUS',
  "a. iankovskaia": 'RUS',
  "a. ibragimova": 'RUS',
  "a. kachmazov": 'RUS',
  "a. kalinskaya": 'RUS',
  "a. karatsev": 'RUS',
  "a. kartseva": 'RUS',
  "a. korneeva": 'RUS',
  "a. kostina": 'RUS',
  "a. kubareva": 'RUS',
  "a. kukasian": 'RUS',
  "a. kunitsyn": 'RUS',
  "a. lizunova": 'RUS',
  "a. mozgaleva": 'RUS',
  "a. pavlyuchenkova": 'RUS',
  "a. pozarenko": 'RUS',
  "a. pushkareva": 'RUS',
  "a. rublev": 'RUS',
  "a. sabalenka": 'BLR',
  "a. sasnovich": 'BLR',
  "a. sedysheva": 'RUS',
  "a. shcherbinina": 'RUS',
  "a. shkutova": 'RUS',
  "a. snigireva": 'RUS',
  "a. tikhonova": 'RUS',
  "a. trynkina": 'RUS',
  "a. varaksina": 'RUS',
  "a. vasileva": 'RUS',
  "a. vatutin": 'RUS',
  "a. yuneva": 'RUS',
  "a. zakharova": 'RUS',
  "a. zgirovsky": 'BLR',
  "a. zolotareva": 'RUS',
  "aleksander chayka": 'RUS',
  "aleksandra iankovskaia": 'RUS',
  "aleksandra pozarenko": 'RUS',
  "alevtina ibragimova": 'RUS',
  "alexander zgirovsky": 'BLR',
  "alexey aleshchev": 'RUS',
  "alexey dubinin": 'RUS',
  "alexey vatutin": 'RUS',
  "aliaksandra sasnovich": 'BLR',
  "alibek kachmazov": 'RUS',
  "alina korneeva": 'RUS',
  "alina shcherbinina": 'RUS',
  "alina tikhonova": 'RUS',
  "alina trynkina": 'RUS',
  "alina yuneva": 'RUS',
  "aliona falei": 'BLR',
  "alisa danilova": 'RUS',
  "alisa vasileva": 'RUS',
  "amina anshba": 'RUS',
  "anastasia efremova": 'RUS',
  "anastasia gasanova": 'RUS',
  "anastasia lizunova": 'RUS',
  "anastasia mozgaleva": 'RUS',
  "anastasia pavlyuchenkova": 'RUS',
  "anastasia tikhonova": 'RUS',
  "anastasia zakharova": 'RUS',
  "anastasia zolotareva": 'RUS',
  "anastasiia gureva": 'RUS',
  "andrei kunitsyn": 'RUS',
  "andrey chepelev": 'RUS',
  "andrey rublev": 'RUS',
  "anna bazderova": 'RUS',
  "anna kalinskaya": 'RUS',
  "anna kartseva": 'RUS',
  "anna kubareva": 'RUS',
  "anna pushkareva": 'RUS',
  "anna sedysheva": 'RUS',
  "anna shkutova": 'RUS',
  "anna snigireva": 'RUS',
  "anton arzhankin": 'RUS',
  "anton chekhov": 'RUS',
  "arina arifullina": 'RUS',
  "arina bulatova": 'RUS',
  "arina kostina": 'RUS',
  "arina varaksina": 'RUS',
  "artem alekseychuk": 'RUS',
  "artur kukasian": 'RUS',
  "aryna sabalenka": 'BLR',
  "aslan karatsev": 'RUS',
  "b. atlangeriev": 'RUS',
  "b. seleznev": 'RUS',
  "bekkhan atlangeriev": 'RUS',
  "bogdan seleznev": 'RUS',
  "d. astakhova": 'RUS',
  "d. belyaeva": 'RUS',
  "d. bessonov": 'RUS',
  "d. bogatov": 'RUS',
  "d. burtsev": 'RUS',
  "d. dolzhenkov": 'RUS',
  "d. egorova": 'RUS',
  "d. golubev": 'RUS',
  "d. khomutsianskaya": 'RUS',
  "d. klok": 'RUS',
  "d. kudashova": 'RUS',
  "d. lodikova": 'RUS',
  "d. medvedev": 'RUS',
  "d. ostapenkov": 'BLR',
  "d. panarin": 'RUS',
  "d. shnaider": 'RUS',
  "d. stepanov": 'RUS',
  "d. zelinskaya": 'RUS',
  "daniil bogatov": 'RUS',
  "daniil golubev": 'RUS',
  "daniil medvedev": 'RUS',
  "daniil ostapenkov": 'BLR',
  "daniil stepanov": 'RUS',
  "danil panarin": 'RUS',
  "daria belyaeva": 'RUS',
  "daria egorova": 'RUS',
  "daria khomutsianskaya": 'RUS',
  "daria kudashova": 'RUS',
  "daria lodikova": 'RUS',
  "daria zelinskaya": 'RUS',
  "darya astakhova": 'RUS',
  "denis klok": 'RUS',
  "diana shnaider": 'RUS',
  "dmitrii burtsev": 'RUS',
  "dmitry bessonov": 'RUS',
  "dmitry dolzhenkov": 'RUS',
  "e. agafonov": 'RUS',
  "e. alexandrova": 'RUS',
  "e. andreeva": 'RUS',
  "e. arutiunian": 'RUS',
  "e. burdina": 'RUS',
  "e. dotsenko": 'RUS',
  "e. gerasimov": 'BLR',
  "e. karlovskiy": 'RUS',
  "e. kazionova": 'RUS',
  "e. khayrutdinova": 'RUS',
  "e. khodzhaeva": 'RUS',
  "e. khotchenkov": 'RUS',
  "e. kuznetsova": 'RUS',
  "e. laskevich": 'BLR',
  "e. maklakova": 'RUS',
  "e. mamedova": 'RUS',
  "e. nepliy": 'RUS',
  "e. ovcharenko": 'RUS',
  "e. philippov": 'RUS',
  "e. pleshivtsev": 'RUS',
  "e. pridankina": 'RUS',
  "e. reyngold": 'RUS',
  "e. shcherbakov": 'RUS',
  "e. tiurnev": 'RUS',
  "e. tupitsyna": 'RUS',
  "e. yashina": 'RUS',
  "edda mamedova": 'RUS',
  "egor agafonov": 'RUS',
  "egor gerasimov": 'BLR',
  "egor khotchenkov": 'RUS',
  "egor pleshivtsev": 'RUS',
  "egor shcherbakov": 'RUS',
  "ekaterina alexandrova": 'RUS',
  "ekaterina dotsenko": 'RUS',
  "ekaterina kazionova": 'RUS',
  "ekaterina khayrutdinova": 'RUS',
  "ekaterina khodzhaeva": 'RUS',
  "ekaterina kuznetsova": 'RUS',
  "ekaterina maklakova": 'RUS',
  "ekaterina ovcharenko": 'RUS',
  "ekaterina reyngold": 'RUS',
  "ekaterina tupitsyna": 'RUS',
  "ekaterina yashina": 'RUS',
  "elena pridankina": 'RUS',
  "elina nepliy": 'RUS',
  "erik arutiunian": 'RUS',
  "erika andreeva": 'RUS',
  "evgenii tiurnev": 'RUS',
  "evgeniya burdina": 'RUS',
  "evgeny karlovskiy": 'RUS',
  "evgeny philippov": 'RUS',
  "evialina laskevich": 'BLR',
  "f. dorofeeva-rybas": 'RUS',
  "f. sosedkin": 'RUS',
  "fedor sosedkin": 'RUS',
  "felitsata dorofeeva-rybas": 'RUS',
  "g. shebekin": 'RUS',
  "grigory shebekin": 'RUS',
  "i. denisov": 'RUS',
  "i. dorokhov": 'RUS',
  "i. gakhov": 'RUS',
  "i. gretskiy": 'RUS',
  "i. iutkin": 'RUS',
  "i. ivashka": 'RUS',
  "i. kudriashov": 'RUS',
  "i. nedelko": 'RUS',
  "i. shymanovich": 'BLR',
  "i. simakin": 'RUS',
  "igor kudriashov": 'RUS',
  "ilia simakin": 'RUS',
  "ilya ivashka": 'RUS',
  "iryna shymanovich": 'BLR',
  "ivan denisov": 'RUS',
  "ivan dorokhov": 'RUS',
  "ivan gakhov": 'RUS',
  "ivan gretskiy": 'RUS',
  "ivan iutkin": 'RUS',
  "ivan nedelko": 'RUS',
  "j. avdeeva": 'RUS',
  "j. khramtsova": 'RUS',
  "j. kolodynska": 'BLR',
  "jana kolodynska": 'BLR',
  "julia avdeeva": 'RUS',
  "julia khramtsova": 'RUS',
  "k. bataikina": 'RUS',
  "k. belkova": 'RUS',
  "k. dmitruk": 'BLR',
  "k. khachanov": 'RUS',
  "k. kivattsev": 'RUS',
  "k. kroitor": 'RUS',
  "k. krupenina": 'RUS',
  "k. laskutova": 'RUS',
  "k. liutova": 'RUS',
  "k. matushkina": 'RUS',
  "k. meshcheryakova": 'RUS',
  "k. pavlova": 'RUS',
  "k. ruchkina": 'RUS',
  "k. sarkisova": 'RUS',
  "k. sidorova": 'RUS',
  "k. smirnova": 'RUS',
  "k. yersh": 'RUS',
  "k. zaytseva": 'RUS',
  "k. zhzhenov": 'RUS',
  "karen khachanov": 'RUS',
  "karine sarkisova": 'RUS',
  "kira bataikina": 'RUS',
  "kira matushkina": 'RUS',
  "kira pavlova": 'RUS',
  "kirill kivattsev": 'RUS',
  "konstantin zhzhenov": 'RUS',
  "kristiana sidorova": 'RUS',
  "kristina belkova": 'RUS',
  "kristina dmitruk": 'BLR',
  "kristina kroitor": 'RUS',
  "kristina liutova": 'RUS',
  "ksenia krupenina": 'RUS',
  "ksenia laskutova": 'RUS',
  "ksenia meshcheryakova": 'RUS',
  "ksenia smirnova": 'RUS',
  "ksenia zaytseva": 'RUS',
  "kseniia ruchkina": 'RUS',
  "kseniya yersh": 'RUS',
  "l. samsonova": 'RUS',
  "liudmila samsonova": 'RUS',
  "m. andreeva": 'RUS',
  "m. andrienko": 'RUS',
  "m. borisiouk": 'BLR',
  "m. elesin": 'RUS',
  "m. golovina": 'RUS',
  "m. haliak": 'BLR',
  "m. kalyakina": 'RUS',
  "m. khodorchenko": 'RUS',
  "m. kononova": 'RUS',
  "m. kozyreva": 'RUS',
  "m. krivoshchekov": 'RUS',
  "m. masiianskaia": 'RUS',
  "m. medvedeva": 'RUS',
  "m. mikhailova": 'RUS',
  "m. mikhaylova": 'RUS',
  "m. salbiev": 'RUS',
  "m. sharipov": 'RUS',
  "m. sholokhova": 'RUS',
  "m. tkacheva": 'RUS',
  "m. tsapenko": 'RUS',
  "m. zhabrailova": 'RUS',
  "m. zhukov": 'RUS',
  "makar elesin": 'RUS',
  "makar krivoshchekov": 'RUS',
  "marat salbiev": 'RUS',
  "marat sharipov": 'RUS',
  "maria andrienko": 'RUS',
  "maria golovina": 'RUS',
  "maria kalyakina": 'RUS',
  "maria kononova": 'RUS',
  "maria kozyreva": 'RUS',
  "maria mikhailova": 'RUS',
  "maria mikhaylova": 'RUS',
  "maria sholokhova": 'RUS',
  "mariia masiianskaia": 'RUS',
  "mariia tkacheva": 'RUS',
  "martin borisiouk": 'BLR',
  "maxim zhukov": 'RUS',
  "mikalai haliak": 'BLR',
  "mikhail khodorchenko": 'RUS',
  "mikhail tsapenko": 'RUS',
  "milana zhabrailova": 'RUS',
  "miroslava medvedeva": 'RUS',
  "mirra andreeva": 'RUS',
  "n. ianin": 'RUS',
  "n. ivanova": 'RUS',
  "n. sozaonova": 'RUS',
  "n. vylegzhanin": 'RUS',
  "nelli ivanova": 'RUS',
  "nikita ianin": 'RUS',
  "nikolay vylegzhanin": 'RUS',
  "nina sozaonova": 'RUS',
  "p. biryukov": 'RUS',
  "p. iatcenko": 'RUS',
  "p. kaibekova": 'RUS',
  "p. kotov": 'RUS',
  "p. kuharenko": 'RUS',
  "p. lagutin": 'RUS',
  "p. leykina": 'RUS',
  "p. skopintseva": 'RUS',
  "pavel kotov": 'RUS',
  "pavel lagutin": 'RUS',
  "petr bar biryukov": 'RUS',
  "polina iatcenko": 'RUS',
  "polina kaibekova": 'RUS',
  "polina kuharenko": 'RUS',
  "polina leykina": 'RUS',
  "polina skopintseva": 'RUS',
  "r. kastsiukevich": 'BLR',
  "r. kharlamov": 'RUS',
  "r. safiullin": 'RUS',
  "r. serazhetdinov": 'RUS',
  "r. tiukaev": 'RUS',
  "r. zolotareva": 'RUS',
  "rada zolotareva": 'RUS',
  "roman kharlamov": 'RUS',
  "roman safiullin": 'RUS',
  "ruslan kastsiukevich": 'BLR',
  "ruslan serazhetdinov": 'RUS',
  "ruslan tiukaev": 'RUS',
  "s. betov": 'BLR',
  "s. gulin": 'RUS',
  "s. ivanov": 'RUS',
  "s. lansere": 'RUS',
  "s. martianova": 'RUS',
  "s. pankin": 'RUS',
  "s. petrov": 'RUS',
  "s. rybkin": 'RUS',
  "s. suslova": 'RUS',
  "saveliy ivanov": 'RUS',
  "savva rybkin": 'RUS',
  "semen pankin": 'RUS',
  "sergey betov": 'BLR',
  "sergey petrov": 'RUS',
  "sofia martianova": 'RUS',
  "sofia suslova": 'RUS',
  "sofya lansere": 'RUS',
  "svyatoslav gulin": 'RUS',
  "t. derepasko": 'RUS',
  "t. prozorova": 'RUS',
  "tatiana prozorova": 'RUS',
  "timofei derepasko": 'RUS',
  "u. hrabavets": 'BLR',
  "u. ignatik": 'BLR',
  "u. lekomtseva": 'RUS',
  "u. tarasevich": 'BLR',
  "uladzimir ignatik": 'BLR',
  "uladzislau tarasevich": 'BLR',
  "ulyana hrabavets": 'BLR',
  "ustiniya lekomtseva": 'RUS',
  "v. artemeva": 'RUS',
  "v. azarenka": 'BLR',
  "v. borodulina": 'RUS',
  "v. diatchenko": 'RUS',
  "v. kudermetova": 'RUS',
  "v. manukyan": 'RUS',
  "v. milovanova": 'RUS',
  "v. mincheva": 'RUS',
  "v. miroshnichenko": 'RUS',
  "v. osminkin": 'RUS',
  "v. ovchinnikov": 'RUS',
  "v. panshina": 'RUS',
  "v. savinykh": 'RUS',
  "v. yushchenko": 'RUS',
  "v. zvonareva": 'RUS',
  "valeria savinykh": 'RUS',
  "valeriia artemeva": 'RUS',
  "valeriya yushchenko": 'RUS',
  "vardan manukyan": 'RUS',
  "varvara panshina": 'RUS',
  "vera zvonareva": 'RUS',
  "veronica miroshnichenko": 'RUS',
  "veronika kudermetova": 'RUS',
  "viacheslav ovchinnikov": 'RUS',
  "victoria azarenka": 'BLR',
  "victoria borodulina": 'RUS',
  "victoria milovanova": 'RUS',
  "vitalia diatchenko": 'RUS',
  "vlada mincheva": 'RUS',
  "vladimir osminkin": 'RUS',
  "y. demin": 'RUS',
  "y. hatouka": 'BLR',
  "y. perapekhina": 'RUS',
  "y. shyla": 'BLR',
  "yaraslav shyla": 'BLR',
  "yaroslav demin": 'RUS',
  "yuliya hatouka": 'BLR',
  "yuliya perapekhina": 'RUS',
};
