export type TennisTour = 'ATP' | 'WTA';

export type TennisMatchRow = {
  matchId: string;
  tour: TennisTour;
  season: number;
  tourneyId: string;
  tourneyName: string;
  tourneyLevel: string;
  isGrandSlam: boolean;
  surface: string;
  date: string | null;
  tourneyDate: string | null;
  round: string;
  score: string;
  bestOf: number;
  minutes: number | null;
  drawSize: number | null;
  playerId: string;
  playerName: string;
  opponentId: string;
  opponent: string;
  opponentIoc: string | null;
  opponentRank: number | null;
  opponentRankPoints: number | null;
  playerRank: number | null;
  rankPoints: number | null;
  seed: number | null;
  entry: string | null;
  height: number | null;
  age: number | null;
  isWin: boolean;
  result: string;
  team: string;
  teamCode: string;
  venue: string | null;
  isHome: boolean;
  moneyline: number;
  gamesWon: number | null;
  gamesLost: number | null;
  totalGames: number | null;
  spread: number | null;
  setsWon: number | null;
  setsLost: number | null;
  totalSets: number | null;
  dominanceRatio: number | null;
  aces: number | null;
  opponentAces: number | null;
  totalAces: number | null;
  doubleFaults: number | null;
  servePoints: number | null;
  serveGames: number | null;
  firstServesIn: number | null;
  firstServesWon: number | null;
  secondServeAttempts: number | null;
  secondServesWon: number | null;
  firstServePct: number | null;
  firstServeWonPct: number | null;
  secondServeWonPct: number | null;
  servicePointsWonPct: number | null;
  breakPointsSaved: number | null;
  breakPointsFaced: number | null;
  breakPointsSavedPct: number | null;
  breakPointsConverted: number | null;
  breakPointsConvertedPct: number | null;
  returnPointsWon: number | null;
  returnPointsWonPct: number | null;
  pointsWon: number | null;
  servePointsWon: number | null;
  totalPoints: number | null;
  hand: string | null;
  opponentHand: string | null;
  ioc: string | null;
  winners?: number | null;
  unforcedErrors?: number | null;
  netPointsWon?: number | null;
  netPointsWonPct?: number | null;
  serviceGamesWon?: number | null;
  returnGamesWon?: number | null;
  firstServeSpeed?: number | null;
  secondServeSpeed?: number | null;
  distanceCovered?: number | null;
  matchPointsSaved?: number | null;
  firstReturnPointsWonPct?: number | null;
  secondReturnPointsWonPct?: number | null;
};

export type TennisPlayer = {
  playerId: string;
  name: string;
  tour: TennisTour;
  ioc: string | null;
  hand: string | null;
  height: number | null;
  rank: number | null;
  rankPoints: number | null;
  imageUrl?: string | null;
};

export type TennisRankingRow = {
  pos: number;
  playerId: string;
  name: string;
  tour: TennisTour;
  points: number | null;
  ioc: string | null;
};
