/**
 * World Cup / international team flag resolution.
 *
 * Flags are served from ESPN's country logo CDN, which is keyed by FIFA-style
 * 3-letter codes (e.g. `ger`, `ned`, `crc`). Data sources give us a mix of:
 *   - BDL country_code (often ISO alpha-3 or FIFA)
 *   - ISO alpha-2 codes
 *   - full country names (international_teams.team_name, e.g. "Germany")
 *
 * Resolution order for any input:
 *   1. Verified overrides from `data/world-cup-flag-map.json` (generated by
 *      `scripts/build-world-cup-flag-map.ts`, validated against the live CDN).
 *   2. Comprehensive built-in ISO/name → FIFA maps below.
 *   3. ISO alpha-3 identity (lowercased) as a last resort.
 *
 * Run `npm run build:world-cup:flag-map` to refresh the verified overrides.
 */
import flagMap from '@/data/world-cup-flag-map.json';

const GENERATED_BY_CODE: Record<string, string> = (flagMap?.byCode as Record<string, string>) ?? {};
const GENERATED_BY_NAME: Record<string, string> = (flagMap?.byName as Record<string, string>) ?? {};

/** ISO alpha-2 → FIFA/ESPN 3-letter code. */
export const FIFA_ISO2_TO_CODE: Record<string, string> = {
  af: 'afg', al: 'alb', dz: 'alg', ad: 'and', ao: 'ang', ai: 'aia', ag: 'atg',
  ar: 'arg', am: 'arm', aw: 'aru', au: 'aus', at: 'aut', az: 'aze', bs: 'bah',
  bh: 'bhr', bd: 'ban', bb: 'brb', by: 'blr', be: 'bel', bz: 'blz', bj: 'ben',
  bm: 'ber', bt: 'bhu', bo: 'bol', ba: 'bih', bw: 'bot', br: 'bra', vg: 'vgb',
  bn: 'bru', bg: 'bul', bf: 'bfa', bi: 'bdi', kh: 'cam', cm: 'cmr', ca: 'can',
  cv: 'cpv', ky: 'cay', cf: 'cta', td: 'cha', cl: 'chi', cn: 'chn', co: 'col',
  km: 'com', cg: 'cgo', cd: 'cod', ck: 'cok', cr: 'crc', ci: 'civ', hr: 'cro',
  cu: 'cub', cw: 'cuw', cy: 'cyp', cz: 'cze', dk: 'den', dj: 'dji', dm: 'dma',
  do: 'dom', ec: 'ecu', eg: 'egy', sv: 'slv', gq: 'eqg', er: 'eri', ee: 'est',
  sz: 'swz', et: 'eth', fo: 'fro', fj: 'fij', fi: 'fin', fr: 'fra', gf: 'guf',
  ga: 'gab', gm: 'gam', ge: 'geo', de: 'ger', gh: 'gha', gi: 'gib', gr: 'gre',
  gd: 'grn', gp: 'glp', gu: 'gum', gt: 'gua', gn: 'gui', gw: 'gnb', gy: 'guy',
  ht: 'hai', hn: 'hon', hk: 'hkg', hu: 'hun', is: 'isl', in: 'ind', id: 'idn',
  ir: 'irn', iq: 'irq', ie: 'irl', il: 'isr', it: 'ita', jm: 'jam', jp: 'jpn',
  jo: 'jor', kz: 'kaz', ke: 'ken', ki: 'kir', kw: 'kuw', kg: 'kgz', la: 'lao',
  lv: 'lva', lb: 'lbn', ls: 'les', lr: 'lbr', ly: 'lby', li: 'lie', lt: 'ltu',
  lu: 'lux', mo: 'mac', mg: 'mad', mw: 'mwi', my: 'mas', mv: 'mdv', ml: 'mli',
  mt: 'mlt', mh: 'mhl', mq: 'mtq', mr: 'mtn', mu: 'mri', mx: 'mex', fm: 'fsm',
  md: 'mda', mc: 'mon', mn: 'mng', me: 'mne', ms: 'msr', ma: 'mar', mz: 'moz',
  mm: 'mya', na: 'nam', nr: 'nru', np: 'nep', nl: 'ned', nc: 'ncl', nz: 'nzl',
  ni: 'nca', ne: 'nig', ng: 'nga', kp: 'prk', mk: 'mkd', no: 'nor', om: 'oma',
  pk: 'pak', pw: 'plw', ps: 'ple', pa: 'pan', pg: 'png', py: 'par', pe: 'per',
  ph: 'phi', pl: 'pol', pt: 'por', pr: 'pur', qa: 'qat', ro: 'rou', ru: 'rus',
  rw: 'rwa', kn: 'skn', lc: 'lca', vc: 'vin', ws: 'sam', sm: 'smr', st: 'stp',
  sa: 'ksa', sn: 'sen', rs: 'srb', sc: 'sey', sl: 'sle', sg: 'sin', sk: 'svk',
  si: 'svn', sb: 'sol', so: 'som', za: 'rsa', kr: 'kor', ss: 'ssd', es: 'esp',
  lk: 'sri', sd: 'sud', sr: 'sur', se: 'swe', ch: 'sui', sy: 'syr', tw: 'tpe',
  tj: 'tjk', tz: 'tan', th: 'tha', tl: 'tls', tg: 'tog', to: 'tga', tt: 'tri',
  tn: 'tun', tr: 'tur', tm: 'tkm', tc: 'tca', tv: 'tuv', ug: 'uga', ua: 'ukr',
  ae: 'uae', gb: 'eng', us: 'usa', uy: 'uru', uz: 'uzb', vu: 'van', ve: 'ven',
  vn: 'vie', ye: 'yem', zm: 'zam', zw: 'zim',
};

/** ISO alpha-3 → FIFA/ESPN code, only where they differ from the FIFA code. */
export const FIFA_ISO3_TO_CODE: Record<string, string> = {
  dza: 'alg', ago: 'ang', atg: 'atg', bgd: 'ban', brb: 'brb', bhr: 'bhr',
  bih: 'bih', bwa: 'bot', bgr: 'bul', bfa: 'bfa', khm: 'cam', cpv: 'cpv',
  caf: 'cta', tcd: 'cha', chl: 'chi', chn: 'chn', cod: 'cod', cog: 'cgo',
  cri: 'crc', hrv: 'cro', cuw: 'cuw', cze: 'cze', dnk: 'den', deu: 'ger',
  gnq: 'eqg', est: 'est', swz: 'swz', eth: 'eth', fro: 'fro', gmb: 'gam',
  grc: 'gre', grd: 'grn', gtm: 'gua', gin: 'gui', gnb: 'gnb', hti: 'hai',
  hnd: 'hon', hkg: 'hkg', idn: 'idn', irn: 'irn', irq: 'irq', irl: 'irl',
  isl: 'isl', jpn: 'jpn', kaz: 'kaz', prk: 'prk', kor: 'kor', kwt: 'kuw',
  kgz: 'kgz', lao: 'lao', lva: 'lva', lbn: 'lbn', lso: 'les', lbr: 'lbr',
  lby: 'lby', ltu: 'ltu', mac: 'mac', mdg: 'mad', mwi: 'mwi', mys: 'mas',
  mdv: 'mdv', mli: 'mli', mlt: 'mlt', mrt: 'mtn', mus: 'mri', mex: 'mex',
  mda: 'mda', mng: 'mng', mne: 'mne', mar: 'mar', moz: 'moz', mmr: 'mya',
  nam: 'nam', npl: 'nep', nld: 'ned', nzl: 'nzl', nic: 'nca', ner: 'nig',
  nga: 'nga', mkd: 'mkd', nor: 'nor', omn: 'oma', pak: 'pak', pse: 'ple',
  pan: 'pan', png: 'png', pry: 'par', per: 'per', phl: 'phi', pol: 'pol',
  prt: 'por', pri: 'pur', qat: 'qat', rou: 'rou', rus: 'rus', rwa: 'rwa',
  ksa: 'ksa', sau: 'ksa', sen: 'sen', srb: 'srb', syc: 'sey', sle: 'sle',
  sgp: 'sin', svk: 'svk', svn: 'svn', slb: 'sol', som: 'som', zaf: 'rsa',
  ssd: 'ssd', esp: 'esp', lka: 'sri', sdn: 'sud', sur: 'sur', swe: 'swe',
  che: 'sui', syr: 'syr', twn: 'tpe', tjk: 'tjk', tza: 'tan', tha: 'tha',
  tls: 'tls', tgo: 'tog', tto: 'tri', tun: 'tun', tur: 'tur', tkm: 'tkm',
  uga: 'uga', ukr: 'ukr', are: 'uae', gbr: 'eng', usa: 'usa', ury: 'uru',
  uzb: 'uzb', ven: 'ven', vnm: 'vie', yem: 'yem', zmb: 'zam', zwe: 'zim',
  slv: 'slv', ecu: 'ecu', egy: 'egy', cmr: 'cmr', gha: 'gha', civ: 'civ',
  jam: 'jam', can: 'can', aus: 'aus', aut: 'aut', bel: 'bel', fra: 'fra',
  ita: 'ita', eng: 'eng', sco: 'sco', wal: 'wal', nir: 'nir', bra: 'bra',
  arg: 'arg', col: 'col', bol: 'bol', alb: 'alb', arm: 'arm', aze: 'aze',
  blr: 'blr', cyp: 'cyp', fin: 'fin', geo: 'geo', hun: 'hun', isr: 'isr',
  jor: 'jor', lux: 'lux', and: 'and', lie: 'lie', smr: 'smr', gib: 'gib',
  ben: 'ben', bdi: 'bdi', com: 'com', dji: 'dji', eri: 'eri', gab: 'gab',
  ken: 'ken',
};

/** Full / common country name → FIFA/ESPN code. */
export const FIFA_NAME_TO_CODE: Record<string, string> = {
  afghanistan: 'afg', albania: 'alb', algeria: 'alg', andorra: 'and', angola: 'ang',
  'antigua and barbuda': 'atg', argentina: 'arg', armenia: 'arm', aruba: 'aru',
  australia: 'aus', austria: 'aut', azerbaijan: 'aze', bahamas: 'bah', bahrain: 'bhr',
  bangladesh: 'ban', barbados: 'brb', belarus: 'blr', belgium: 'bel', belize: 'blz',
  benin: 'ben', bermuda: 'ber', bhutan: 'bhu', bolivia: 'bol',
  'bosnia and herzegovina': 'bih', 'bosnia & herzegovina': 'bih', botswana: 'bot',
  brazil: 'bra', brunei: 'bru', bulgaria: 'bul', 'burkina faso': 'bfa', burundi: 'bdi',
  cambodia: 'cam', cameroon: 'cmr', canada: 'can', 'cape verde': 'cpv',
  'cabo verde': 'cpv', 'cape verde islands': 'cpv', 'cabo verde islands': 'cpv',
  'central african republic': 'cta', chad: 'cha', chile: 'chi',
  china: 'chn', 'china pr': 'chn', colombia: 'col', comoros: 'com', congo: 'cgo',
  'congo dr': 'cod', 'dr congo': 'cod', 'democratic republic of the congo': 'cod',
  'congo democratic republic': 'cod', 'cook islands': 'cok', 'costa rica': 'crc',
  'cote d ivoire': 'civ', "cote d'ivoire": 'civ', 'ivory coast': 'civ', croatia: 'cro',
  cuba: 'cub', curacao: 'cuw', 'curaçao': 'cuw', cyprus: 'cyp', 'czech republic': 'cze',
  czechia: 'cze', denmark: 'den', djibouti: 'dji', dominica: 'dma',
  'dominican republic': 'dom', ecuador: 'ecu', egypt: 'egy', 'el salvador': 'slv',
  'equatorial guinea': 'eqg', eritrea: 'eri', estonia: 'est', eswatini: 'swz',
  swaziland: 'swz', ethiopia: 'eth', 'faroe islands': 'fro', fiji: 'fij',
  finland: 'fin', france: 'fra', 'french guiana': 'guf', gabon: 'gab', gambia: 'gam',
  'the gambia': 'gam', georgia: 'geo', germany: 'ger', ghana: 'gha', gibraltar: 'gib',
  greece: 'gre', grenada: 'grn', guadeloupe: 'glp', guam: 'gum', guatemala: 'gua',
  guinea: 'gui', 'guinea-bissau': 'gnb', 'guinea bissau': 'gnb', guyana: 'guy',
  haiti: 'hai', honduras: 'hon', 'hong kong': 'hkg', hungary: 'hun', iceland: 'isl',
  india: 'ind', indonesia: 'idn', iran: 'irn', 'ir iran': 'irn', iraq: 'irq',
  ireland: 'irl', 'republic of ireland': 'irl', 'rep of ireland': 'irl', israel: 'isr',
  italy: 'ita', kosovo: 'kos',
  jamaica: 'jam', japan: 'jpn', jordan: 'jor', kazakhstan: 'kaz', kenya: 'ken',
  kiribati: 'kir', kuwait: 'kuw', kyrgyzstan: 'kgz', 'kyrgyz republic': 'kgz',
  laos: 'lao', latvia: 'lva', lebanon: 'lbn', lesotho: 'les', liberia: 'lbr',
  libya: 'lby', liechtenstein: 'lie', lithuania: 'ltu', luxembourg: 'lux',
  macau: 'mac', macao: 'mac', madagascar: 'mad', malawi: 'mwi', malaysia: 'mas',
  maldives: 'mdv', mali: 'mli', malta: 'mlt', 'marshall islands': 'mhl',
  martinique: 'mtq', mauritania: 'mtn', mauritius: 'mri', mexico: 'mex',
  micronesia: 'fsm', moldova: 'mda', monaco: 'mon', mongolia: 'mng',
  montenegro: 'mne', montserrat: 'msr', morocco: 'mar', mozambique: 'moz',
  myanmar: 'mya', namibia: 'nam', nauru: 'nru', nepal: 'nep', netherlands: 'ned',
  'new caledonia': 'ncl', 'new zealand': 'nzl', nicaragua: 'nca', niger: 'nig',
  nigeria: 'nga', 'north korea': 'prk', 'korea dpr': 'prk', 'korea republic': 'kor',
  'north macedonia': 'mkd', macedonia: 'mkd', 'fyr macedonia': 'mkd',
  'northern ireland': 'nir', norway: 'nor',
  oman: 'oma', pakistan: 'pak', palau: 'plw', palestine: 'ple', panama: 'pan',
  'papua new guinea': 'png', paraguay: 'par', peru: 'per', philippines: 'phi',
  poland: 'pol', portugal: 'por', 'puerto rico': 'pur', qatar: 'qat', romania: 'rou',
  russia: 'rus', rwanda: 'rwa', 'saint kitts and nevis': 'skn', 'saint lucia': 'lca',
  'saint vincent and the grenadines': 'vin', samoa: 'sam', 'san marino': 'smr',
  'sao tome and principe': 'stp', 'saudi arabia': 'ksa', senegal: 'sen', serbia: 'srb',
  seychelles: 'sey', 'sierra leone': 'sle', singapore: 'sin', slovakia: 'svk',
  slovenia: 'svn', 'solomon islands': 'sol', somalia: 'som', 'south africa': 'rsa',
  'south korea': 'kor', 'south sudan': 'ssd', spain: 'esp', 'sri lanka': 'sri',
  sudan: 'sud', suriname: 'sur', sweden: 'swe', switzerland: 'sui', syria: 'syr',
  'chinese taipei': 'tpe', taiwan: 'tpe', tajikistan: 'tjk', tanzania: 'tan',
  thailand: 'tha', 'timor-leste': 'tls', 'timor leste': 'tls', togo: 'tog',
  tonga: 'tga', 'trinidad and tobago': 'tri', tunisia: 'tun', turkey: 'tur',
  'türkiye': 'tur', turkmenistan: 'tkm', 'turks and caicos islands': 'tca',
  tuvalu: 'tuv', uganda: 'uga', ukraine: 'ukr', 'united arab emirates': 'uae',
  'united states': 'usa', 'united states of america': 'usa', usa: 'usa', uruguay: 'uru',
  uzbekistan: 'uzb', vanuatu: 'van', venezuela: 'ven', vietnam: 'vie', 'viet nam': 'vie',
  'british virgin islands': 'vgb', 'us virgin islands': 'vir', wales: 'wal',
  yemen: 'yem', zambia: 'zam', zimbabwe: 'zim', england: 'eng', scotland: 'sco',
};

function normalizeName(input: string): string {
  return String(input || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

/**
 * `FIFA_NAME_TO_CODE` keyed by the normalized form of each name, so lookups for
 * inputs containing punctuation/connectors (e.g. "Bosnia & Herzegovina",
 * "Cote d'Ivoire") match keys stored with "and"/apostrophes.
 */
const NORMALIZED_NAME_TO_CODE: Record<string, string> = Object.entries(
  FIFA_NAME_TO_CODE
).reduce<Record<string, string>>((acc, [name, code]) => {
  const key = normalizeName(name);
  if (key && !acc[key]) acc[key] = code;
  return acc;
}, {});

/** Synonym groups for matching team labels from different data sources. */
const WC_TEAM_ALIAS_GROUPS: string[][] = [
  ['cape verde', 'cabo verde', 'cape verde islands', 'cabo verde islands', 'cpv', 'cv'],
  ['ivory coast', 'cote d ivoire', 'cote divoire', 'civ'],
  ['usa', 'united states', 'united states of america'],
  ['south korea', 'korea republic', 'kor'],
  ['iran', 'ir iran', 'irn'],
  ['netherlands', 'holland', 'ned'],
  ['czech republic', 'czechia', 'cze'],
  ['dr congo', 'congo dr', 'democratic republic of the congo', 'cod'],
  ['new zealand', 'nzl'],
  ['ghana', 'gha'],
  ['turkey', 'turkiye', 'tur'],
];

function worldCupTeamNameKeys(input: string): string[] {
  const raw = String(input || '').trim();
  if (!raw) return [];
  const keys = new Set<string>();
  keys.add(raw);
  keys.add(normalizeName(raw));
  const norm = normalizeName(raw);
  if (norm.endsWith(' islands')) keys.add(norm.replace(/ islands$/, '').trim());
  if (norm.endsWith(' national team')) keys.add(norm.replace(/ national team$/, '').trim());
  return [...keys].filter(Boolean);
}

/** True when two team labels refer to the same nation (name, code, or alias group). */
export function worldCupTeamsMatch(a: string, b: string): boolean {
  const rawA = String(a || '').trim();
  const rawB = String(b || '').trim();
  if (!rawA || !rawB) return false;

  const slugA = resolveWorldCupFlagCode(rawA);
  const slugB = resolveWorldCupFlagCode(rawB);
  if (slugA && slugB && slugA === slugB) return true;

  const keysA = new Set(worldCupTeamNameKeys(rawA));
  const keysB = new Set(worldCupTeamNameKeys(rawB));
  for (const key of keysA) {
    if (keysB.has(key)) return true;
  }

  const na = normalizeName(rawA);
  const nb = normalizeName(rawB);
  if (na && nb && (na === nb || na.includes(nb) || nb.includes(na))) return true;

  for (const group of WC_TEAM_ALIAS_GROUPS) {
    const inA = group.some((alias) => keysA.has(alias) || keysA.has(normalizeName(alias)) || slugA === alias);
    const inB = group.some((alias) => keysB.has(alias) || keysB.has(normalizeName(alias)) || slugB === alias);
    if (inA && inB) return true;
  }

  return false;
}

/**
 * Resolve any team identifier (FIFA code, ISO2, ISO3, or country name) to the
 * ESPN flag slug. Returns null when nothing matches so callers can fall back to
 * an abbreviation badge.
 */
export function resolveWorldCupFlagCode(
  input?: string | null,
  opts?: { allowIdentity?: boolean }
): string | null {
  const raw = String(input || '').trim();
  if (!raw) return null;
  const lower = raw.toLowerCase();

  // 1. Verified overrides (exact code, then normalized name and common variants).
  if (GENERATED_BY_CODE[lower]) return GENERATED_BY_CODE[lower];
  for (const key of worldCupTeamNameKeys(raw)) {
    if (GENERATED_BY_NAME[key]) return GENERATED_BY_NAME[key];
  }

  // 2. Built-in maps.
  if (lower.length === 2 && FIFA_ISO2_TO_CODE[lower]) return FIFA_ISO2_TO_CODE[lower];
  if (lower.length === 3) {
    if (FIFA_ISO3_TO_CODE[lower]) return FIFA_ISO3_TO_CODE[lower];
  }
  for (const key of worldCupTeamNameKeys(raw)) {
    if (FIFA_NAME_TO_CODE[key]) return FIFA_NAME_TO_CODE[key];
    const fromNormalizedName = NORMALIZED_NAME_TO_CODE[key];
    if (fromNormalizedName) return fromNormalizedName;
  }

  // 3. ISO alpha-3 identity (many FIFA codes equal ISO-3 lowercased). This is a
  // best-effort guess and can produce invalid CDN slugs for name-derived
  // abbreviations (e.g. "SOU"), so callers can disable it via allowIdentity.
  if ((opts?.allowIdentity ?? true) && lower.length === 3 && /^[a-z]{3}$/.test(lower)) {
    return lower;
  }

  return null;
}

export function getWorldCupFlagUrl(
  input?: string | null,
  opts?: { allowIdentity?: boolean }
): string | null {
  const code = resolveWorldCupFlagCode(input, opts);
  if (!code) return null;
  return `https://a.espncdn.com/combiner/i?img=/i/teamlogos/countries/500/${code}.png&h=80&w=80`;
}

/**
 * Resolve the best ESPN flag slug for a team, preferring verified name/code
 * mappings over the loose ISO-3 identity guess. Tries the country name and code
 * through the strict maps first (so a name-derived abbreviation like "SOU" can't
 * shadow the real "South Korea" → kor lookup), then allows the identity guess.
 */
export function resolveBestWorldCupFlagUrl(
  ...candidates: Array<string | null | undefined>
): string | null {
  for (const candidate of candidates) {
    const url = getWorldCupFlagUrl(candidate, { allowIdentity: false });
    if (url) return url;
  }
  for (const candidate of candidates) {
    const url = getWorldCupFlagUrl(candidate);
    if (url) return url;
  }
  return null;
}
